name: Maven Build and Unit Tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: mint-latest  # The operating system for the runner
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'  # You can change this to any distribution you prefer

      # Step 3: Cache Maven dependencies to speed up builds (optional)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Cache Maven's local repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/pom.xml') }}  # Cache key is based on the pom.xml files
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Run Maven build and unit tests
      - name: Run Maven tests
        run: mvn clean test  # Run Maven clean and unit tests (mvn test runs unit tests by default)

      # Step 5: (Optional) Upload test results as artifacts (if needed)
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/test-classes  # Adjust the path if your tests generate results elsewhere
